mysite/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("seller",include("ecom.controller")),
    path("",include("custom.controller")),

]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/mysite/custom/models.py
from django.db import models

# Create your models here.

mysite/mysite/ecom/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.fields.files import FileField
from django.urls import reverse
# Create your models here.

# model for seller
class Seller(models.Model):
    name=models.CharField(max_length=100)
    company=models.CharField(max_length=100,unique=True,help_text='Enter the company name')
    phone=models.CharField(max_length=10)
    email=models.EmailField()
    address=models.TextField(max_length=1000)
    password=models.CharField(max_length=200,default=0)
    def __str__(self):
        return f'company:{self.company} name:{self.name}'

# models for category
class Category(models.Model):
    name=models.CharField(max_length=100,unique=True)
    image=models.FileField()
    def __str__(self):
        return f"category:{self.name}"


# model for subcategory
class SubCategory(models.Model):
    catid=models.ForeignKey(Category,on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    image=models.FileField()
    def __str__(self):
        return f"sub-category:{self.name}"

# models for category
class Product(models.Model):
    name=models.CharField(max_length=100)
    brand=models.CharField(max_length=100)
    desc=models.TextField(max_length=1000)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    discount=models.IntegerField()
    image=models.FileField()
    slid=models.ForeignKey(Seller, on_delete=models.CASCADE)
    subid=models.ForeignKey(SubCategory,on_delete=models.CASCADE)
    def __str__(self):
        return f"name:{self.name} brand:{self.brand}"
    def get_absolute_url(self):
        return reverse("ecom:home")


mysite/mysite/custom/templates/custom/forms.py
from django import from .forms import 
from django.contrib.auth.models import User

class CReg(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)
    re_password=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model=User
        fields=['username','email','first_name','last_name']
    def clean(self):
        super(CReg,self).clean()
        p=self.cleaned_data.get("password")
        p1=self.cleaned_data.get("re_password")
        if p!=p1:
            raise forms.ValidationError("password didn't match")

mysite/mysite/custom/controller.py
from django.urls import path
from . import views
app_name='custom'
urlpatterns = [
    path("",views.Home.as_view(),name='main'),
]

mysite/mysite/custom/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from ecom.models import Product,Category
from django.views import generic
from django.contrib.auth.models import User
from .forms import CReg
'''def home(request):
    c=Category.objects.all()
    return render(request,"custom/home.html",{'cat':c})
'''

class Home(generic.ListView):
    template_name="custom/home.html"
    context_object_name='cat'
    def get_queryset(self):
        return Category.objects.all()
    
class Register(generic.Views):
    def get(self,request):
        return render(request,"custom/reg.html",{'form':CReg(None)})
    def post(self,request):
        f=CReg(request.POST)
        if f.is_valid():
            data=f.save(commit=False)
            p=f.cleaned_data.get("password")
            data.set_password(p)
            data.save()
            return HttpResponse("user created")
        return render(request,"custom/reg.html",{'form':f})

mysite/mysite/ecom/controller.py
from django.urls import path
from . import views
app_name='ecom'
urlpatterns = [
    path("",views.Home.as_view(),name='home'),
    path('register/',views.SignupSel,name='signup'),
    path('login/',views.signinseller,name='signin'),
    path("logout/",views.logouts,name='signout'),
    path("product/<int:pk>",views.Addproduct.as_view(),name='addproduct'),
    path("product/update/<int:pk>",views.Upproduct.as_view(),name='upproduct'),
    path("product/delete/<int:pk>",views.Delproduct.as_view(),name='delproduct'),
    path("subcategory/productview/<int:pk>",views.Subdetail.as_view(),name='detail'),
]

mysite/mysite/ecom/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Product, Seller,Category, SubCategory
from .myforms import SelSignup, Sellerlogin
from django.contrib.auth.hashers import make_password
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
def SignupSel(request):
    f=SelSignup(request.POST or None)
    
    if f.is_valid():
        sel=f.save(commit=False)
        p=f.cleaned_data.get('password')
        sel.password=make_password(p)
        sel.save()
        return redirect("ecom:signin")
    return render(request,'ecom/sellerreg.html',{'form':f})


def signinseller(request):
    f=Sellerlogin(request.POST or None)
    if f.is_valid():
        c = f.cleaned_data.get("company")
        obj=Seller.objects.get(company=c)
        request.session['user_log']={'name':obj.name,"company":obj.company}
        return redirect("ecom:home")
    return render(request,'ecom/sellerreg.html',{'form':f})

class Home(ListView):
    template_name="ecom/home.html"
    context_object_name='cat'
    def get_queryset(self):
        selid=self.request.session.get("user_log")
        if selid:
            sell=Seller.objects.get(company=selid.get("company"))
            return {'cate':Category.objects.all(),
            'prod':Product.objects.filter(slid=sell)} 
        else:
            return None
def logouts(request):
    request.session.pop("user_log")
    return redirect("ecom:home")


class Addproduct(CreateView):
    template_name='ecom/addproduct.html'
    model=Product
    fields=['name','brand','desc','price','discount','image']
    context_object_name='form'
    def form_valid(self,form):
        subid=self.kwargs.get("pk")
        sub=SubCategory.objects.get(id=subid)
        selid=self.request.session.get("user_log")
        sell=Seller.objects.get(company=selid.get("company"))
        form.instance.slid=sell
        form.instance.subid=sub
        return super().form_valid(form)
        
class Upproduct(UpdateView):
    template_name='ecom/addproduct.html'
    model=Product
    fields=['name','brand','desc','price','discount','image']
    context_object_name='form'

class Delproduct(DeleteView):
    template_name='ecom/delproduct.html'
    model=Product
    context_object_name='prod'
    success_url=reverse_lazy("ecom:home")
    success_message='producet deleted'


class Subdetail(ListView):
    template_name='ecom/subview.html'
    model=SubCategory
    context_object_name='data'
    def get_queryset(self):
        selid=self.request.session.get("user_log")
        subid=self.kwargs.get("pk")
        sub=SubCategory.objects.get(id=subid)
        if selid:
            sell=Seller.objects.get(company=selid.get("company"))
            return {'sub':sub,'prod':Product.objects.filter(slid=sell,subid=sub)} 
        else:
            return None

mysite/mysite/custom/templates/custom/home.html
{% extends "custom/master.html"%}
{%block title%} homepage{%endblock%} 
{%block body%}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="container-fluid">
	  
	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav me-auto mb-2 mb-lg-0">
		 {% for i in cat%} 
		  <li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
			  {{i.name}}
			</a>
			<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
			  {%for j in i.subcategory_set.all%}
				<li><a class="dropdown-item" href="{% url 'ecom:detail' j.id%}">{{j.name}}</a></li>
				{%endfor%}
			</ul>
		  </li>
		  {%endfor%}
		</ul>
		</div>
	</div>
  </nav>

  <div class='row'>
	{%for j in cat%}
    {%for n in j.subcategory_set.all%}
    {%for k in n.product_set.all%}
	<div class='column'>
  <div class="card" style="width: 18rem;">
	<img src="{{k.image.url}}" class="card-img-top" alt="...">
	<div class="card-body">
	  <h5 class="card-title">{{n.name}},{{n.brand}}</h5>
	  <h6>{{k.price}},{{k.discount}}%</h6>
	  <p>{{k.desc}}</p> 
	  <p>
	  <a href="#" class="btn btn-primary">view</a>
	  	   </p>
	</div>
  </div>
  </div>
  {%endfor%}
  {%endfor%}
  {%endfor%}
  </div>

{%endblock%}

mysite/mysite/custom/templates/custom/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>{%block title%} {%endblock%}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: deepskyblue;">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Apni Dukan</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      {%block body%} 
      {%endblock%}
</body>
</html>

mysite/mysite/ecom/templates/ecom/addproduct.html
{%extends "ecom/sellermaster.html"%}
{%block title%} ADD PRODUCT{%endblock%}
{%block body%}
<form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table table-bordered">
            {{form.as_table}}
        </table>
        <input type="submit" value='Submit' />
    </form>
{%endblock%}

mysite/mysite/ecom/templates/ecom/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Dashboard</title>
</head>
<body>
    <h1>
    <form method="POST" enctype="multipart/form-data">
        <!-- csrf token -->
        {% csrf_token %}

        <!-- for getting form as paragraf
        {{form.as_p}} -->

        {% comment %} <table class="table table-bordered">
            {{form.as_table}}
        </table> {% endcomment %}

        <!-- form submit button -->
        <input type="submit" value='Submit' />
    </form>

</body>
</html>

mysite/mysite/ecom/templates/ecom/delproduct.html
{%extends "ecom/sellermaster.html"%}
{%block title%}DELETE PRODUCT{%endblock%}
{%block body%}
<form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class='row'>
	
	<div class='column'>
  <div class="card" style="width: 18rem;">
	<img src="{{prod.image.url}}" class="card-img-top" alt="...">
	<div class="card-body">
	  <h5 class="card-title">{{prod.name}},{{prod.brand}}</h5>
	  <h6>{{prod.price}},{{prod.discount}}%</h6>
	  <p>{{prod.desc}}</p> 
	 <input type="submit" value='Submit'>
    </div>
  </div>
  </div>
  </div>   
    </form>
    {{message}}
{%endblock%}

mysite/mysite/ecom/templates/ecom/home.html
{% extends 'ecom/sellermaster.html'%} 
{%block title%} Seller homepage{%endblock%}
{%block body%}
{%if 'user_log' in request.session%}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="container-fluid">
	  
	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav me-auto mb-2 mb-lg-0">
		 {% for i in cat.cate%} 
		  <li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
			  {{i.name}}
			</a>
			<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
			  {%for j in i.subcategory_set.all%}
				<li><a class="dropdown-item" href="{% url 'ecom:detail' j.id%}">{{j.name}}</a></li>
				{%endfor%}
			</ul>
		  </li>
		  {%endfor%}
		</ul>
		</div>
	</div>
  </nav>
<div class='row'>
	{%for j in cat.prod%}
	<div class='column'>
  <div class="card" style="width: 18rem;">
	<img src="{{j.image.url}}" class="card-img-top" alt="...">
	<div class="card-body">
	  <h5 class="card-title">{{j.name}},{{j.brand}}</h5>
	  <h6>{{j.price}},{{j.discount}}%</h6>
	  <p>{{j.desc}}</p> 
	  <p>
	  <a href="{% url 'ecom:upproduct' j.id%}" class="btn btn-primary">update</a>
	  <a href="{% url 'ecom:delproduct' j.id%}" class="btn btn-primary">delete</a>
	   </p>
	</div>
  </div>
  </div>
  {%endfor%}
  </div>

{%else%}
{%endif%}

{%endblock%}

mysite/mysite/ecom/templates/ecom/sellermaster.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>{%block title%} {%endblock%}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{%url 'ecom:home'%}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              
              {% if "user_log" in request.session%}

              <li class="nav-item">
                <a class="nav-link active" href="#">{{request.session.user_log.company}}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{%url 'ecom:signout'%}">logout</a>
              </li>
              {%else%}
              <li class="nav-item">
                <a class="nav-link active" href="{%url 'ecom:signup'%}">signup</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{%url 'ecom:signin'%}">signin</a>
              </li>         
              {%endif%}    
            </ul>
            </div>
        </div>
      </nav>
      {%block body%}{%endblock%} 
       
</body>
</html>

mysite/mysite/ecom/templates/ecom/sellerreg.html
{%extends "ecom/sellermaster.html"%}
{%block title%} SELLER SIGNUP{%endblock%}
{%block body%}
<form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table table-bordered">
            {{form.as_table}}
        </table>
        <input type="submit" value='Submit' />
    </form>
{%endblock%}

mysite/mysite/ecom/templates/ecom/subview.html
{% extends 'ecom/sellermaster.html'%} 
{%block title%} {{data.sub.name}}{%endblock%}
{%block body%}
{%if 'user_log' in request.session%}
<div>
    <p><h5>{{data.sub.name}}</h5><a href="{% url 'ecom:addproduct' data.sub.id%}" class="btn btn-primary">Addproduct</a> </p>
</div>
<div class='row'>
	{%for j in data.prod%}
	<div class='column'>
  <div class="card" style="width: 18rem;">
	<img src="{{j.image.url}}" class="card-img-top" alt="...">
	<div class="card-body">
	  <h5 class="card-title">{{j.name}},{{j.brand}}</h5>
	  <h6>{{j.price}},{{j.discount}}%</h6>
	  <p>{{j.desc}}</p> 
	  <p>
	  <a href="{% url 'ecom:upproduct' j.id%}" class="btn btn-primary">update</a>
	  <a href="{% url 'ecom:delproduct' j.id%}" class="btn btn-primary">delete</a>
	   </p>
	</div>
  </div>
  </div>
  {%endfor%}
  </div>

{%else%}
{%endif%}

{%endblock%}